export default
    [
        {
            name: 'Piłka',
            price: 10,
            date: '09.06 14:00',
            address: 'Warszawa, Rozbrat 26',
            discipline: 'football',
            location: {lat: 52.1976, lng: 20.8814},
        },
        {
            name: 'Siata',
            price: 15,
            date: '09.06 15:00',
            address: 'Warszawa, Miedziana 8',
            discipline: 'volleyball',
            location: {lat: 52.1776, lng: 20.9814}
        },
        {
            name: 'Piłka na hali',
            price: 8,
            date: '10.06 14:00',
            address: 'Warszawa, Nowowiejska 37B',
            discipline: 'football',
            location: {lat: 52.5776, lng: 20.3814},
        },
        {
            name: 'Kosz',
            price: 20,
            date: '09.06 14:00',
            address: 'Warszawa, Gen. S. Kaliskiego 2',
            discipline: 'basketball',
            location: {lat: 52.5776, lng: 20.8814},
        },
        {
            name: 'Piłka',
            price: 0,
            date: '09.06 14:00',
            address: 'Warszawa, M. Keniga 20',
            discipline: 'football',
            location: {lat: 50.8823, lng: 20.5845},
        },
        {
            name: 'Tenis',
            price: 15,
            date: '09.06 14:00',
            address: 'Kielce, Krakowska 15',
            discipline: 'tennis',
            location: {lat: 50.6823, lng: 20.0845},
        },
        {
            name: 'Gra',
            price: 12,
            date: '09.06 14:00',
            address: 'Kielce, Żytnia 1',
            discipline: 'bicycle',
            location: {lat: 51.0823, lng: 20.5845},
        },
        {
            name: 'Gra',
            price: 8,
            date: '09.06 14:00',
            address: 'Kielce, Warszawska 20',
            discipline: 'football'
        },
        {
            name: 'Gra',
            price: 11,
            date: '09.06 14:00',
            address: 'Kielce, Tarnowska 18',
            discipline: 'basketball',
            location: {lat: 50.7664, lng: 20.5498},
        },
        {
            name: 'Gra',
            price: 13,
            date: '09.06 14:00',
            address: 'Kielce, Krakowska 25',
            discipline: 'football',
            location: {lat: 50.8664, lng: 20.4498},
        },
        {
            name: 'Gra',
            price: 5,
            date: '09.06 14:00',
            address: 'Poznań, Głogowska 18',
            discipline: 'tennis',
            location: {lat: 52.3976, lng: 20.6814},
        },
        {
            name: 'Gra',
            price: 30,
            date: '09.06 14:00',
            address: 'Poznań, Bukowska 31',
            discipline: 'bicycle',
            location: {lat: 52.3976, lng: 16.6229},
        },
        {
            name: 'Gra',
            price: 20,
            date: '09.06 14:00',
            address: 'Poznań, Słowiańska 22',
            discipline: 'football',
            location: {lat: 52.4116, lng: 17.0229},
        },
        {
            name: 'Gra',
            price: 11,
            date: '09.06 14:00',
            address: 'Poznań, Winogrady 8',
            discipline: 'basketball',
            location: {lat: 52.4176, lng: 17.1229},
        },
        {
            name: 'Gra',
            price: 15,
            date: '09.06 14:00',
            address: 'Poznań, Kazimierza Wielkiego 3',
            discipline: 'football',
            location: {lat: 52.3516, lng: 16.8229},
        },
        {
            name: 'Gra',
            price: 10,
            date: '09.06 14:00',
            address: 'Gdańsk, Powstańców Warszawskich 8',
            discipline: 'tennis',
            location: {lat: 54.3570, lng: 18.6285}
        },
        {
            name: 'Gra',
            price: 10,
            date: '09.06 14:00',
            address: 'Gdańsk, 3 Maja 21',
            discipline: 'football',
            location: {lat: 54.3587, lng: 18.6416}
        },
        {
            name: 'Gra',
            price: 0,
            date: '09.06 14:00',
            address: 'Gdańsk, Rolna 8',
            discipline: 'volleyball',
            location: {lat: 54.3842, lng: 18.5807}
        },
        {
            name: 'Gra',
            price: 15,
            date: '09.06 14:00',
            address: 'Gdańsk, Warszawska 18',
            discipline: 'tennis',
            location: {lat: 54.3320, lng: 18.5760}
        },
        {
            name: 'Gra',
            price: 11,
            date: '09.06 14:00',
            address: 'Gdańsk, Grodza Kamienna 28',
            discipline: 'bicycle',
            location: {lat: 54.3395, lng: 18.6501}
        },
    ]